### ISSUE TITLE
subtract proejction

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-cryosparc2#102]
Subtract projection uses as input a set of particles and as output another set. For a given particle the id (and name) of the input particle is different from the id of the output particle. In addition the CTF information is lost in the process, therefore the output particles have no CTF. 

Question: How can a recover the CTF information? I do not think this is possible with the actual implementation.

**Comment by pconesa** [comment]
thanks @rmarabini !

We can see that cryosparc is outputting items in different order. But our output has ctf information.
![image](https://user-images.githubusercontent.com/785633/152985883-a0068bce-fde7-454e-8c5b-a20fda6760db.png)


Your concern about the ids (that actually are not kept) was to make a CTF match or for other reason.

Why you do not have ctf?  Our test are done on devel but it was recently released. Maybe your plugin is not updated?

**Comment by rmarabini** [comment]
Uhmm @pconesa , let my update scipion  and scipion-em-cryosparc and I will recheck this CTF issue

**Comment by rmarabini** [comment]
hi @pconesa , you are right CTF information is there
