### ISSUE TITLE
use cryosparc output as relion input

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em-cryosparc2#144]
Hi @pconesa, @fonsecareyna82 and @azazellochg,

Let me explain a problem that appears when you try to use the output of "cryosparc 3D-non uniform refinement" (and I guess any other refinement) as input for "relion 3D autorefine" (and I guess any 3D refine).  That is, when I further refine using relion (with the option "consider previous alignment" set to True) a setOfParticles created by cryosparc.  In my test case the particle has I2 symmetry. 

Relion and cryosparc handle symmetry in a different way, Relion takes advantage of the symmetry and, for I2 symmetry, only searches in 1/60 of all possible projection directions while cryosparc covers all the sphere. In this way if you plot the projection directions in the Relion case you see that all projection direction are concentrated in a small triangle defined by 2 5fold symmetry axis and 1 3fold symmetry axis while Cryosparc shows points in all directions. 

So, what happens when relion reads the cryosparc data? Since relion only has information for the projection directions inside the non redundant part of the projection sphere, it will take the  cryospac projection directions and  assign then the value of the closest relion-valid projection direction (I hope I has been able to explain myself). In general, the closest valid projection direction is not close to the original projection and the  reconstruction is a shapeless sphere. 

I have created a script that takes as input the cryosparc setOfParticles and the symmetry and produces a setOfPArticles that Relion likes. The question now is how to incorporate this script in Scipion. The first option, that I dislike a lot, is create a protocol called "adapt setof particles for Scipion", The second option would be to decide what convention Scipion is going to follow and adapt the protocols to it. In this way if Scipion follows Relion convention then cryosparc needs to rearrange the setOfPraticles projection directions before saving them. On the other hand if Scipion follows cryosparc convention then relion protocols need to preprocess the projection direction before using them. 

If the decision was mine I would choose relion conventions as scipion conventions and modify the output of cryosparc. 
what do you think?

**Comment by pconesa** [comment]
Yes but this is already done in C's. So this issue is fixed right?

**Comment by rmarabini** [comment]
Actually this is done in python but yes, it is fixed.
