### ISSUE TITLE
plugin fails to locate ssd

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-cryosparc2#4]
I'm using cryosparc 2.11.0. I know it's probably unsupported version, but the error is not related to that. The problem is obviously I don't have /ssd on my local pc where I launch the job, ssd is supposed to be on a worker lane. Why does it look on a local pc?

Another question: how scipion queue system relates to lane parameter in cryosparc?
```
00010:   Traceback (most recent call last):
00011:     File "/net/nfs1/public/EM/Scipion/scipion-2.0.0/pyworkflow/protocol/protocol.py", line 186, in run
00012:       self._run()
00013:     File "/net/nfs1/public/EM/Scipion/scipion-2.0.0/pyworkflow/protocol/protocol.py", line 1283, in _run
00014:       self._insertAllSteps()  # Define steps for execute later
00015:     File "/net/nfs1/public/EM/Scipion/scipion-2.0.0/software/lib/python2.7/site-packages/cryosparc2/protocols/protocol_cryorefine.py", line 318, in _insertAllSteps
00016:       self._initializeCryosparcProject()
00017:     File "/net/nfs1/public/EM/Scipion/scipion-2.0.0/software/lib/python2.7/site-packages/cryosparc2/protocols/protocol_cryorefine.py", line 527, in _initializeCryosparcProject
00018:       folderPaths = getProjectPath(self.projectPath)
00019:     File "/net/nfs1/public/EM/Scipion/scipion-2.0.0/software/lib/python2.7/site-packages/cryosparc2/utils.py", line 129, in getProjectPath
00020:       folderPaths = os.listdir(projectDir)
00021:   OSError: [Errno 2] No such file or directory: '/ssd/ProjCryoSparc_TestCryosparcParticlesSubtract'
```

**Comment by fonsecareyna82** [comment]
1. Hi Gregory. If you don't have ssd in your local pc, you need to change the value of "Cache  particle 
    images on SSD" to "No" in the Compute settings tab. Maybe, by default, we need to put this value 
    to No.

**Comment by azazellochg** [comment]
Hi! So the plugin works only locally?

**Comment by fonsecareyna82** [comment]
Sorry Gregory, the ssd_path is only used by cryosparc software installation(you don't worry about that). The software uses it to make calculations and other performance operations.
The problem is that we nemed by mistake the CRYOSSD_DIR variable assuming that the projects were created to the cry SSD folder. We must change that variable and name it CRYOSPROJECT_DIR. This variable must be accessible by the cryosparc master and the worker because all the outputs generated by cryosparc are copied in that path

**Comment by azazellochg** [comment]
Ah, alright, it makes sense that this is the project dir and not ssd path. Thanks, I'll try again!
