### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by dzyla** [scipion-em/scipion-em-cryosparc2#8]
Hey,

This error is preventing the cryosparc2 plugin installation:

` error when importing from cryosparc2.protocols: No module named pandas
   File "/mnt/data1/Programs/scipion/software/lib/python2.7/site-packages/cryosparc2/convert/convert.py", line 28, in <module>
   Check the plugin manager (Configuration->Plugins in Scipion manager window)
   or use 'scipion installp --help --checkUpdates' in the command line to check for upgrades,
   it could be a versions compatibility issue.
`

What might be the reason of this error and how I could easily fix it? Thanks!

Best,
Dawid

**Comment by dzyla** [comment]
Using :

`./scipion` installp -p `scipion-em-cryosparc2`

gives the problem with pyem installation:

`Building scipy-016 ...
/mnt/data1/Programs/scipion/software/bin/python /mnt/data1/Programs/scipion/software/lib/python2.7/site-packages/pip install scipy==0.16
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: scipy==0.16 in ./software/lib/python2.7/site-packages (0.16.0)
WARNING: You are using pip version 19.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Done (0.47 seconds)
Building pyem ...
pip install git+https://github.com/asarnow/pyem.git@d46691bcacae63043346e98cec9ff7b621ca1427
/bin/sh: /mnt/data1/Programs/scipion/software/bin/pip: /root/Yunior/scipion/software/bin/python: bad interpreter: Permission denied
Traceback (most recent call last):
  File "/mnt/data1/Programs/scipion/pyworkflow/install/install-plugin.py", line 224, in <module>
    plugin.installBin(args=['-j', numberProcessor])
  File "/mnt/data1/Programs/scipion/pyworkflow/install/plugin_funcs.py", line 157, in installBin
    environment.execute()
  File "/mnt/data1/Programs/scipion/pyworkflow/install/funcs.py", line 787, in execute
    self._executeTargets(targetList)
  File "/mnt/data1/Programs/scipion/pyworkflow/install/funcs.py", line 725, in _executeTargets
    tgt.execute()
  File "/mnt/data1/Programs/scipion/pyworkflow/install/funcs.py", line 212, in execute
    command.execute()
  File "/mnt/data1/Programs/scipion/pyworkflow/install/funcs.py", line 156, in execute
    "running '%s')" % (t, cmd))
AssertionError: target '/mnt/data1/Programs/scipion/software/lib/python2.7/site-packages/pyem' not built (after running 'pip install git+https://github.com/asarnow/pyem.git@d46691bcacae63043346e98cec9ff7b621ca1427')
`

**Comment by pconesa** [comment]
Thanks @dmaluenda for assigning this to us. I missed it completely.

@dzyla , what happens if you do:

scipion python -m pip install git+https://github.com/asarnow/pyem.git@d46691bcacae63043346e98cec9ff7b621ca1427


This has worked for me right now.

**Comment by pconesa** [comment]
Wait I¡'m seeing this again: /root/Yunior/scipion/software/bin/python:

**Comment by pconesa** [comment]
What is the content of /mnt/data1/Programs/scipion/software/bin/pip

**Comment by dzyla** [comment]
Hey,

thank for the answer. The content is:

`#!/root/Yunior/scipion/software/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from pip._internal import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
`

When I changed it to the:
`/mnt/data1/programs/scipion/software/bin/python` it worked!

**Comment by pconesa** [comment]
Great!
